import type { Metadata } from "next";
import './globals.css'; // ou o nome do seu arquivo CSS

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Meta tags adicionais para SEO
  viewport: "width=device-width, initial-scale=1.0",
  keywords: "Next.js, React, App, TODOs",
  authors: [{ name: "Marcos", url: "https://seusite.com" }], // Adicione seu nome e site
  // Outras informações que você pode querer adicionar
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
      </head>
      <body className="bg-gray-900 text-white font-sans"> {/* Classes do Tailwind CSS */}
        {children}
      </body>
    </html>
  );
}
